apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    orgId: 1
    isDefault: true
    basicAuth: false
    jsonData:
      timeInterval: 30s
